### ISSUE TITLE
혹시 사용 가능한 방법인가요?

### ISSUE THREAD

**Issue by Foreist** [domyounglee/korbert-mecab-multigpu#1]
저장소의 sh 내용이랑 readme 내용이랑 조금 다른 것 같고, 없는 파일과 없는 함수들이 언급되어 있어서 여쭈어봅니다.

**Comment by domyounglee** [comment]
네 사용 가능합니다. readme 가 업데이트 되지 않은 부분이 있을 수 있는데 .sh 파일에서 Path 만 맞추시고 
mecab 형태소분석기 api 설치하셔서 url 바꿔주시면 될거에요!
혹시 문제있으면 댓글 달아주세요 :)

**Comment by domyounglee** [comment]
코드랑 README 수정하여 close 합니다.
