### ISSUE TITLE
Is there any published paper describing your work?

### ISSUE THREAD

**Issue by ilya-palachev** [domyounglee/korbert-mecab-multigpu#2]
Hello,

First of all, thank you for publishing this repository. Is there any published paper describing your work? I mean a paper in some journal or conference proceedings. This information would help to understand your work a lot.

Thanks in advance!

**Comment by ilya-palachev** [comment]
And is this repository related to this paper:
Lim J.H., Kim H.K., Kim Y.K. Recent R&D Trends for Pretrained Language Model. *Electronics and Telecommunications Trends*. 2020;35(3):9-19. URL: https://www.koreascience.or.kr/article/JAKO202056463863258.pdf
?

**Comment by domyounglee** [comment]
Hi @ilya-palachev It's rather a project to leverage the shared pretrained BERT model from ETRI where they use a Korean POS tagger before tokenizing the Korean corpus. So there isn't any research work for this repository. Actually the paper you commented is from ETRI that shared the pretrained model.

**Comment by ilya-palachev** [comment]
@domyounglee Thanks for the feedback! Another question: do you know where the ETRI model is published? I cannot find it in GitHub.

**Comment by domyounglee** [comment]
@ilya-palachev You can get the pretrained model at http://aiopen.etri.re.kr/ if you request a key to the administrator and agree with them you're not using it for a profit.

**Comment by ilya-palachev** [comment]
Okay, thanks for information!
